apiVersion: v1
kind: Namespace
metadata:
  name: pepr-system
  labels:
    pepr.dev: ''
    istio-injection: enabled
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pepr-soak-ci
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pepr-soak-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pepr-soak-ci
subjects:
  - kind: ServiceAccount
    name: pepr-soak-ci
    namespace: pepr-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pepr-soak-ci
  namespace: pepr-system
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-soak-ci-api-token
  namespace: pepr-system
type: Opaque
data:
  value: >-
    NGYwZjJmNWM4NzVmYTRkMWZiOWIxNjU3NDJhN2M1MDY1OTkyOWY0YTM0YTIyZDRlZWQ4MmE0MjZiMWEwYjIxYw==
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-soak-ci-tls
  namespace: pepr-system
type: kubernetes.io/tls
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlDcGpDQ0FZNmdBd0lCQWdJQkFUQU5CZ2txaGtpRzl3MEJBUXNGQURBQU1CNFhEVEkwTURneE5ERXpNek16DQpObG9YRFRJMU1EZ3hOREV6TXpNek5sb3dBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DDQpnZ0VCQUxkcU1Nc3lwMGIva1pERzE0U1ozN3JxTERySTFMeWRKbDhyd2dBdFl0d2xqL3ZzMWZRN2lsbTJRaFlxDQpwMkpoUXBHaFpnVEd2aFl4dGdaNnhKWlZwd0wzbVQyWXlBVGI3UFUwaDBJK3hUcm15QzhGZGpJT3dER2NuelcvDQp5M21Ia1dxMU9YSmdkcGNtbkRDZ2ZZYWIzZElOQjVrVEZjbFJMaUpqSTFhaUxDajdBZVVTbzVaSG1YUDZlaUNODQp1d3NvTi9wRDdQQUwzRE9kTStkWHRXTk5ZMzZsckI3b3NTVW5QM1REam9yZFFWUHlEekkrMS9qcWhTMjkwdmVCDQpmYlpseVB0R04xZ0Y2dlJ0RnBiN1pMbVVYL09ldVBDd1V4WlJlR1doRHJUNkRYS2IxNXdFMi9zUDZBdW10RFV1DQpUT0pDT2tOLzBkYmhOTGlyWm92ckJ0QUtCVHNDQXdFQUFhTXJNQ2t3SndZRFZSMFJCQ0F3SG9JY2NHVndjaTF6DQpiMkZyTFdOcExuQmxjSEl0YzNsemRHVnRMbk4yWXpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWN5SUFlZ05XDQpaSFU5Z2lMK0ZuT2RrM0ZaMWk0VGtORGF6K0tWZkQyb0ZrNHBlUGRucGZwZzJlNFZLT1p6bGcrMndxcUw0SU5lDQpRSG1YNnFzZm03ZnFMMlBxdWluczcwRnpGMFEzeTRXTDFpZExWcTZSY1lPT1M1bzJjOVhKZS9OdDVpT2V4U2I1DQptL05WZ2ZMZmZnRFQyMGZUNWpBckR3cFU0ckZ6MWxMM1V3Mi9SZExhVHM5Rkc2MmE4UkRQMXdrRWhkamtkUmQxDQpQc3ZONVFWRitEOWVlU3VkTlN3aGtNa1ZDTVJZWUFnejQ2ZGxIUTNacExxMHEzckN6cUJRWmYrbkx0WG9YcWxXDQpCUTFBelVmaUQ5NWFlaFFPYkE3aFhJSDh6cXEyWjNPZmlJU2tOdnNZOHVvRklNcWVUZWRTbC9tZWZNdExjZkZBDQpyR2U4TC9hQk5tMlZUUT09DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQo=
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRW93SUJBQUtDQVFFQXQyb3d5ektuUnYrUmtNYlhoSm5mdXVvc09zalV2SjBtWHl2Q0FDMWkzQ1dQKyt6Vg0KOUR1S1diWkNGaXFuWW1GQ2thRm1CTWErRmpHMkJuckVsbFduQXZlWlBaaklCTnZzOVRTSFFqN0ZPdWJJTHdWMg0KTWc3QU1aeWZOYi9MZVllUmFyVTVjbUIybHlhY01LQjlocHZkMGcwSG1STVZ5VkV1SW1NalZxSXNLUHNCNVJLag0KbGtlWmMvcDZJSTI3Q3lnMytrUHM4QXZjTTUwejUxZTFZMDFqZnFXc0h1aXhKU2MvZE1PT2l0MUJVL0lQTWo3WA0KK09xRkxiM1M5NEY5dG1YSSswWTNXQVhxOUcwV2x2dGt1WlJmODU2NDhMQlRGbEY0WmFFT3RQb05jcHZYbkFUYg0KK3cvb0M2YTBOUzVNNGtJNlEzL1IxdUUwdUt0bWkrc0cwQW9GT3dJREFRQUJBb0lCQUF1d3ZvY1h1dXdUdW1KTw0KY2pVc1NPNHFkOWc2cmIza2pGUzdsQmx4SUhYUFdtNkxGQllGa2l0bXFsbFhBdnFLZFhUcWVIZFhJdUxhUWZPeA0KY1M5SWYvcDRtcHYvb3NiQWduUWNrdFJ6bU1iemZSQ1dMMTJWd3NWR3YzL0Jza1UrNXFpMUFBSXlIaUpETStoYg0KaWw5V2pFY1Rvb2VDQjd6MXFpbWNtbHpaYUZRbms4WTZRa1R4UDJka1R6YmttMHREd1ZERGhZUnlYRWVraGJaZA0KbE5FVVVScWhxUGxrd3NLYnFhSEN6Zk1ZMXIrWjhITjZMUzBUeDA2UHVieDhmV2puTUlHL3N2aDNqWWJGckk5Qw0KZkE3OXBhci9HZWRaTkROUTRNYU1oWnNabm5NR2lMUWJGT3dLdUR5MHUyU3ZlbWFRL0QxeDBFdVNiLzF3UkVocQ0KRHJ2RnRpVUNnWUVBOElITmYrVHRiZ0xFaHFnS3pJeWpQUXhGUmVBbFRDcGZvM2l6L0ZNbFVyU3RYL1ZnTVRVWg0KRHRjL250ckliejRsejlwZmpvSE5KVjFzZ2pqaEZzMm5jNzdzR2hvZUxBOXFiWUJNYXJGNHJjdnp1MTF0SDRmaw0KQW1yVUJpbGxFVEdBSXpWeTlhT2I3Y1RRZGd2UW8wNWVhQ2RWaEcvc2NXZGNPS0Mzcms0cTMvY0NnWUVBd3pyaA0KZjkvV0ZwdFhlbHVxeVZKN2xwL2Rtam1IL3M4KzdudFQvVXR6eXdkYUJXVUJzL1R1cjBRL0kvc0w2YjY2N2xscQ0KdmpxNGVZWEsyMmtoSzFpZE8rc2ErZ1hveEh0MjRPSUpWOW5sZitHOEhhRjBKOFNVS3RQZ1puMFFYdC9XdnBERQ0KbWdYM0YxbmVNWktNeThNWTFadUxRd2dQeEFKekhyZ1Q2RXN0ZTkwQ2dZQVZ2SFY1SUpTQXc4bEZManpEbmRaRw0KOXl2dms4RnJMODB5OWY2MlNFRndSeG9BT1NuM2FJZ2FPa1BxdEhVMjhKUDBSQlVzeVBoa2J4d1diTk9TL3dVcQ0KUmRBS3o5OTROZkIxY3duMC9wTWNpZmsrTHNSay9DQVVROWxqc1N3TU1NQVc3b2EwUXBRZUdoS0pDS3BUaUFxcQ0KT1J2V2UxTVFNTG81OS9TQjBWaTRvd0tCZ0Jlb25RY29Fd091VTQyS2FrbjNhdTYzOU56cHQrZFRLaWN3WHQ5Rg0KTTRVWklQbWlZZkJ5OERIaExWMm80S3EwNkdaV0E2K0Y0akVuMjR0M1ZBT3l1MnMxZEpGMEFkODlyd3hWbUJoRA0KV2FLRHNvNU1zSXpaTDdONDlhcTE0VFArSUVIN3ZUZUZIWXFBNDRKU1ppbVRQUUUxMWt5TFA0M2JWaVFVM3FTNQ0KNTRzcEFvR0JBSXNrTnNqdUxYM1BOTXpWZkJNcUFsZ2dhMXp2a1IrbjNOZ1lpSFVuL2JlRVZTS0c2ak9DY2JSaQ0KNlU3ZzlueExPTVpxSVNPS2piOWNkZE1BWmpCMEZPdmtNWldaK2NuazBYMFN4TnB1VXNncmlMcmNRL3BnUlZ1OA0KY3hBREZ1eVcxNk5EdnJIaldGU216N2tUZEZOTzM1NThOTDF0WkUwcUQwT0ovd0NUMDMvZw0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0NCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepr-soak-ci
  namespace: pepr-system
  annotations:
    pepr.dev/description: soak test for watch controller
  labels:
    app: pepr-soak-ci
    pepr.dev/controller: admission
    pepr.dev/uuid: soak-ci
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pepr-soak-ci
      pepr.dev/controller: admission
  template:
    metadata:
      annotations:
        buildTimestamp: '1723642415865'
      labels:
        app: pepr-soak-ci
        pepr.dev/controller: admission
    spec:
      terminationGracePeriodSeconds: 5
      priorityClassName: system-node-critical
      serviceAccountName: pepr-soak-ci
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        fsGroup: 65532
      containers:
        - name: server
          image: pepr:dev
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/node_modules/pepr/dist/controller.js
            - d9586c62008f49ccdf4766eb2380e10b4939f3a70dd3f04781790deb9762f680
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          env:
            - name: PEPR_WATCH_MODE
              value: 'false'
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: debug
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: api-token
              mountPath: /app/api-token
              readOnly: true
            - name: module
              mountPath: /app/load
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-soak-ci-tls
        - name: api-token
          secret:
            secretName: pepr-soak-ci-api-token
        - name: module
          secret:
            secretName: pepr-soak-ci-module
---
apiVersion: v1
kind: Service
metadata:
  name: pepr-soak-ci
  namespace: pepr-system
  labels:
    pepr.dev/controller: admission
spec:
  selector:
    app: pepr-soak-ci
    pepr.dev/controller: admission
  ports:
    - port: 443
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pepr-soak-ci-watcher
  namespace: pepr-system
  labels:
    pepr.dev/controller: watcher
spec:
  selector:
    app: pepr-soak-ci-watcher
    pepr.dev/controller: watcher
  ports:
    - port: 443
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: pepr-soak-ci-module
  namespace: pepr-system
type: Opaque
data:
  module-d9586c62008f49ccdf4766eb2380e10b4939f3a70dd3f04781790deb9762f680.js.gz: >-
    H4sIAAAAAAAAE4VTXYtbNxB9z69QpyW5FyTFW1NYtNylkGxLqNNdQtM+LNsiS7O2Yl1J1YfNxdz/XiRvWreE7ZukOXN05szMXkZihtv1J1SZa3w0Du+iDxjzdLWXkYShy9T1w7XpMgUnRwR63EtbUDiqvHs0mxLl2qL4ajH3LcUPEf8sJmIHAUOE02sajjVbwBat9axGWPJyx5QBuseYjHcCFnzBL4BqTCqakNtbRZGMKZNHH8lBZrUlyrscvbUYge5wOviok7g//Udhd5mAQvDWqImh2xiH9V6/HL0utt4SqhJNnoCCcY8+jhjhgZ7ASRyd1yjgeri45Au+gJnWbHEsxeiToqbbu5sYfRQQsRoI9IDrrfe7X8yIvmRxsaCqpOzHlVyjrbRyxBSkQnFserjGPQioIlI2nhlXeYx3IABd9VXDPFNpD3JK7zbORzwjSeL+YabGKVs06h+MbS8U3V4cV7c//rG6+fVmJUDjumwqjcaATqNTppbYKoLfF3y5bBVq3L/9FyBP4akPAr7jS76EmZ7uf2d/NnypWcJcAoh6JsqWlDESjRYzkua8xj15+ZKch1VEeR5mbLdMTMYNecVYU/19wrjHKBavCGMHaXKjKGtU2ZI6AL5kkrLMJRGNwfppRJcJcw3E0pQyjkCVNQJcGEksrhL5uGsGki3agDERZQ1hjLCn+Ri+6cJB90Dr2P2T+YRqs8hYKiYjkdYChYbDbxGeB1fEE7g4k/8H3SDz3NYHv7hUcXB4IMjfyCDXxpo8dc9s2Ze3CuaeHn/bohNqHiK1Q+hkmpwiebg+yup5t6DIf7pMfYdc8juve/7O/fx5CE+CmMbRQ8/fto53uZ8pnLp/5zX0V+osN71pfde38WPQ9dA9Q/gBlXfKWPyvKmK7zEfMUsssea26n/ur6ofndxji+9bJLtH7+NBfvXj9+muSfIkK38sQjNt8/LAazv3hnxIfZXjxF52fDc0SBQAA
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pepr-soak-ci-store
  namespace: pepr-system
rules:
  - apiGroups:
      - pepr.dev
    resources:
      - peprstores
    resourceNames:
      - ''
    verbs:
      - create
      - get
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pepr-soak-ci-store
  namespace: pepr-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pepr-soak-ci-store
subjects:
  - kind: ServiceAccount
    name: pepr-soak-ci-store
    namespace: pepr-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepr-soak-ci-watcher
  namespace: pepr-system
  annotations:
    pepr.dev/description: soak test for watch controller
  labels:
    app: pepr-soak-ci-watcher
    pepr.dev/controller: watcher
    pepr.dev/uuid: soak-ci
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pepr-soak-ci-watcher
      pepr.dev/controller: watcher
  template:
    metadata:
      annotations:
        buildTimestamp: '1723642415865'
      labels:
        app: pepr-soak-ci-watcher
        pepr.dev/controller: watcher
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: pepr-soak-ci
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        fsGroup: 65532
      containers:
        - name: watcher
          image: pepr:dev
          imagePullPolicy: IfNotPresent
          command:
            - node
            - /app/node_modules/pepr/dist/controller.js
            - d9586c62008f49ccdf4766eb2380e10b4939f3a70dd3f04781790deb9762f680
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              scheme: HTTPS
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: module
              mountPath: /app/load
              readOnly: true
          env:
            - name: PEPR_WATCH_MODE
              value: 'true'
            - name: PEPR_PRETTY_LOG
              value: 'false'
            - name: LOG_LEVEL
              value: debug
      volumes:
        - name: tls-certs
          secret:
            secretName: pepr-soak-ci-tls
        - name: module
          secret:
            secretName: pepr-soak-ci-module
