apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-deletion-timestamp1
---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-deletion-timestamp2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ns1-admission
  name: ns1-admission
  namespace: hello-pepr-deletion-timestamp1
spec:
  containers:
  - image: nginx
    name: ns1-admission
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ns1-watch
  name: ns1-watch
  namespace: hello-pepr-deletion-timestamp1
spec:
  containers:
  - image: nginx
    name: ns1-watch
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ns2-admission
  name: ns2-admission
  namespace: hello-pepr-deletion-timestamp2
spec:
  containers:
  - image: nginx
    name: ns2-admission
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ns2-watch
  name: ns2-watch
  namespace: hello-pepr-deletion-timestamp2
spec:
  containers:
  - image: nginx
    name: ns2-watch
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ns2-delete
  name: ns2-delete
  namespace: hello-pepr-deletion-timestamp2
spec:
  containers:
  - image: nginx
    name: ns2-delete
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
