---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-mutate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pass-full
  namespace: hello-pepr-mutate
data:
  glass-is-half: empty

---
apiVersion: v1
kind: Namespace
metadata:
  name: unconcerned

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pass-unconcerned
  namespace: unconcerned
data:
  glass-is-half: empty
