---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-mutate

---
apiVersion: v1
kind: Secret
metadata:
  name: update-yay
  namespace: hello-pepr-mutate
stringData: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: update-meh
  namespace: hello-pepr-mutate
stringData: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: update-oof
  namespace: hello-pepr-mutate
stringData: {}
