// This file is auto-generated by kubernetes-fluent-client, do not edit manually
import { GenericKind, RegisterKind } from "kubernetes-fluent-client";
export class PeprStore extends GenericKind {
  data?: { [key: string]: string };
}

RegisterKind(PeprStore, {
  group: "pepr.dev",
  version: "v1",
  kind: "PeprStore",
  plural: "peprstores",
});
