apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-finalize
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-watch
  namespace: hello-pepr-finalize
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-reconcile
  namespace: hello-pepr-finalize
data: {}
