---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-validate

---
apiVersion: v1
kind: Secret
metadata:
  name: delete-yay
  namespace: hello-pepr-validate
stringData: {}

---
apiVersion: v1
kind: Secret
metadata:
  name: delete-oof
  namespace: hello-pepr-validate
stringData: {}
