---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-validate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fail-oof
  namespace: hello-pepr-validate
data:
  pass: oof

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fail-missing
  namespace: hello-pepr-validate
data: {}

---
apiVersion: v1
kind: Namespace
metadata:
  name: prohibited

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fail-namespace
  namespace: prohibited
data:
  pass: yep