---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-validate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pass-yep
  namespace: hello-pepr-validate
data:
  pass: yep

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pass-yep-default
  namespace: default
data:
  pass: yep