---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-validate

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-1
  namespace: hello-pepr-validate
data:
  pass: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-2
data:
  pass: "true"