---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-store

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: async
  namespace: hello-pepr-store
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sync
  namespace: hello-pepr-store
data: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: observe
  namespace: hello-pepr-store
data: {}

