apiVersion: v1
kind: Namespace
metadata:
  name: pexex-policy-report
---
# Setup the exemption test for the policy report
apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: exemption
  namespace: pexex-policy-report
spec:
  exemptions:
    - policies:
        - Disallow_Privileged
      matcher:
        namespace: pexex-policy-report
        name: "example-bad-pod"
---        
apiVersion: v1
kind: Pod
metadata:
  name: example-good-pod
spec:
  containers:
  - name: myapp
    image: busybox:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: example-bad-pod
spec:
  containers:
  - name: myapp
    image: busybox:latest
