---
apiVersion: v1
kind: Namespace
metadata:
  name: pexex-clusterpolicyreport

---
apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: allow-naughtiness
  namespace: pexex-clusterpolicyreport
spec:
  exemptions:
    - policies:
        - Disallow_Privileged
        - Drop_All_Capabilities
      matcher:
        namespace: pexex-clusterpolicyreport
        name: naughty-pod
    
    - policies:
        - Restrict_Volume_Types
      matcher:
        namespace: pexex-clusterpolicyreport
        name: naughty-pod

---
apiVersion: v1
kind: Pod
metadata:
  name: nice-pod
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'sleep infinity']

---
apiVersion: v1
kind: Pod
metadata:
  name: naughty-pod
  namespace: pexex-clusterpolicyreport
  labels:
    exemptions.uds.dev: v1alpha1
  annotations:
    exemptions.uds.dev/v1alpha1: >-
      Disallow_Privileged
      Drop_All_Capabilities
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'sleep infinity']
