---
apiVersion: v1
kind: Namespace
metadata:
  name: pexex-clusterpolicyreport

---
apiVersion: uds.dev/v1alpha1
kind: Exemption
metadata:
  name: allow-naughtiness
  namespace: pexex-clusterpolicyreport
spec: {}
# resource used to:
# - trigger create / delete of ClusterPolicyReport resource
# - report missing / outdated resource exemption annotations
# resource NOT used to:
# - add exemption annotations to resources (assumes UDS operator will do that)

---
apiVersion: v1
kind: Pod
metadata:
  name: nice-pod
  namespace: default
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'sleep infinity']

---
apiVersion: v1
kind: Pod
metadata:
  name: naughty-pod
  namespace: pexex-clusterpolicyreport
  labels:
    exemptions.uds.dev: v1alpha1
  annotations:
    exemptions.uds.dev/v1alpha1: >-
      pexex-clusterpolicyreport:allow-naughtiness:DisallowPrivileged
      pexex-clusterpolicyreport:allow-naughtiness:DropAllCapabilities
      pexex-clusterpolicyreport:allow-naughtiness:RestrictVolumeTypes
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'sleep infinity']

# TODO
# - Add another exemption annotation that covers the same, existing Pod
# - Add another Pod covered by exemptions
# - Add another non-Exempted Pod
# - Add an Exempted Service, etc.
# - Make sure the Policy Capability registers listening for all types (not just Pod, Service)