apiVersion: v1
kind: Pod
metadata:
  name: not-as-nice-pod
  namespace: default
  labels:
    exemptions.uds.dev: v1alpha1
  annotations:
    exemptions.uds.dev/v1alpha1: >-
      pexex-clusterpolicyreport:allow-naughtiness:DisallowPrivileged
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'sleep infinity']
---
apiVersion: v1
kind: Pod
metadata:
  name: naughty-pod
  namespace: pexex-clusterpolicyreport
  labels:
    exemptions.uds.dev: v1alpha1
  annotations:
    exemptions.uds.dev/v1alpha1: >-
      pexex-clusterpolicyreport:allow-naughtiness:DisallowPrivileged
      pexex-clusterpolicyreport:allow-naughtiness:DropAllCapabilities
      pexex-clusterpolicyreport:allow-naughtiness:RestrictVolumeTypes
      pexex-clusterpolicyreport:allow-naughtiness:RestrictHostPorts
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ['sh', '-c', 'sleep infinity']
# TODO
# - Add another non-Exempted Pod
# - Add an Exempted Service, etc.
# - Make sure the Policy Capability registers listening for all types (not just Pod, Service)