---
apiVersion: v1
kind: Namespace
metadata:
  name: kfc-logs

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: sts-logs
  name: sts-logs
  namespace: kfc-logs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sts-logs
  template:
    metadata:
      labels:
        app: sts-logs
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sts-logs
  name: sts-logs
  namespace: kfc-logs
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sts-logs
