apiVersion: v1
kind: Namespace
metadata:
  name: hello-pepr-reconcile
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-slow
  namespace: hello-pepr-reconcile
data:
  note: A
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-fast
  namespace: hello-pepr-reconcile
data:
  note: D
---
apiVersion: v1
kind: Secret
metadata:
  name: se-slow
  namespace: hello-pepr-reconcile
stringData:
  note: Q
---
apiVersion: v1
kind: Secret
metadata:
  name: se-fast
  namespace: hello-pepr-reconcile
stringData:
  note: T
