name: E2E - Pepr Excellent Examples

permissions: read-all
on:
  workflow_dispatch:
  merge_group:
    paths-ignore:
    - "LICENSE"
    - "CODEOWNERS"
    - "**.md"
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  examples-matrix:
    name: job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.create-matrix.outputs.matrix }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: clone pepr-excellent-examples
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js 22
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22

      - name: create matrix
        run: |
          matrix=$(
            node "$PEPR/.github/workflows/matrix.js" "$(pwd)"
          )
          echo "matrix=${matrix}" >> "$GITHUB_OUTPUT"
        id: create-matrix

  excellent-examples:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs:
      - examples-matrix
    if: needs.examples-matrix.outputs.matrix != ''
    strategy:
      fail-fast: false
      max-parallel: 32 # Roughly matches the number of E2E tests and below GitHub concurrency limit
      matrix: ${{ fromJSON(needs.examples-matrix.outputs.matrix) }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: "install k3d"
        run: "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash"
        shell: bash

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Use Node.js 22
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22

      - name: install pepr-excellent-examples deps
        run: |
          npm ci

      - name: run e2e tests
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 6
          command: |
            npm run --workspace=${{ matrix.name }} test:e2e 
